#bind -n S-down new-window
bind -n S-left prev
bind -n S-right next
#bind -n C-left swap-window -t -1
#bind -n C-right swap-window -t +1

#bind-key -n C-j detach

setw -g mode-keys vi

# Mouse support - set to on if you want to use the mouse
set -g terminal-overrides 'XTerm*:smcup@:rmcup@'

set -g mouse on
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'copy-mode -e'"

# Set the default terminal mode to 256color mode
set -g default-terminal "screen-256color"

# enable activity alerts
setw -g monitor-activity on
set -g visual-activity on

# Center the window list
set -g status-justify centre

# More scrollback
set-option -g history-limit 4000

# Notifications
set -g focus-events on

# Maximize and restore a pane
#unbind Up bind Up new-window -d -n tmp \; swap-pane -s tmp.1 \; select-window -t tmp
#unbind Down
#bind Down last-window \; swap-pane -s tmp.1 \; kill-window -t tmp

set -g update-environment -r
#setenv -g SSH_AUTH_SOCK $HOME/.ssh/ssh_auth_sock.$HOSTNAME

# rate-limiting
#setw -g c0-change-trigger 10
#setw -g c0-change-interval 250

# copy to xclip
#bind C-c run "tmux save-buffer - | xclip -selection c"
#bind C-v run "xclip -o | tmux load-buffer - ; tmux paste-buffer"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-yank'

run '~/.tmux/plugins/tpm/tpm'

